### PR TITLE
Add requirements folder

### PR DESCRIPTION
**Pull request by muraty**

### CODE REVIEW

**Comment by cenkalti** [comment]
What's the benefit of putting requirements files into a folder, can you explain?

**Comment by muraty** [comment]
requirements folder usage is suggested (for example in the book 'two scoops of django') for putting all the requirements text files (local, base, dev, prod, test etc.) under it. It is just a notation I try to apply in my projects. There won't be any real benefit with using it, just a notation. 

If you are not agree with me, you can simply decline this pr.

**Comment by cenkalti** [comment]
Keeping the requirements.txt file in the project root is more widely accepted convention. Here is an example from that book's repo: https://github.com/twoscoops/django-twoscoops-project/blob/develop/requirements.txt

Also I have a similar service (http://www.pypi-notifier.org) that requires requirements.txt files at the root.

**Comment by muraty** [comment]
Thanks for the explanation. But, I guess, I am missing the point. In the above link, the project is still using requirements folder. It keeps requirements.txt file for just those type of services; 
"..because many Platforms as a Service look for requirements.txt in the root directory of a project."
and that file links the files under requirements folder.

So, the usage of current requirements_*.txt files at the root level is not applying the convention ?

**Pull request closed without merging**
