### PR TITLE
Added Windows support (at the cost of disabling some features)

### LINKED ISSUE #54: Windows support
Trying to start Kuyruk on Windows end up with an error due to the missing signals support on Windows:

```
Traceback (most recent call last):
  File "c:\project\tasks\app\run.py", line 26, in run
    app.run()
  File "c:\Anaconda\Win64\envs\env\lib\site-packages\kuyruk\worker.py",
ine 97, in run
    signal.signal(signal.SIGHUP, self._handle_sighup)
AttributeError: module 'signal' has no attribute 'SIGHUP'
```

I am going to try comment out all the signals usage, but even if that works, I believe, it will miss quite a few features... Any ideas on how to work this around for Windows?

P.S. Is Windows support something that you are interested in?

### PR DESCRIPTION
**Pull request by frol**
Closes #54 (read more about the problems and the compromises there)

I have tested it on my Windows server and it works fine there. There should be no change on Linux/MacOS.

### CODE REVIEW

**Comment by cenkalti** [comment]
@frol Do you know why the Travis build fail?

**Comment by frol** [comment]
I have no idea. My change should not affect any platform but Windows.

**Comment by frol** [comment]
@cenkalti The failing test is not related to my changes because I can reproduce it on the latest 8.4.0 commit. For some reason, RabbitMQ returns an empty list (`[]`) on `/api/connections` request if there is no delay (or delay < 5 seconds) after worker start. I couldn't come up with anything but putting a `sleep` before `drop_connection`. The failing tests on Python 3.5 are even more mysterious, I have no clue what is wrong there :(

**Comment by cenkalti** [comment]
Hi @frol. Thank you for investigating the issue with tests. I think tests are not reliable because when I restarted the build on Travis, they completed successfully. Hence, I will be cherry-picking only the first commit from this PR.

**Comment by cenkalti** [comment]
Released a new version: https://pypi.python.org/pypi/Kuyruk/8.5.0

**Comment by frol** [comment]
Thank you!

**Pull request closed without merging**
